#!/bin/bash

QSTATLIST=$(qstat)

i=0

while read -r qline; do
    if [ $i -ge 2 ]
    then
        id=${qline:0:7}
        file="qsub_logs/job.sh.o${id}"
        if [ -f "$file" ]
        then
            while IFS='' read -r line || [[ -n "$line" ]]; do
                if [[ $line == *"Running:"* ]]; then
                   echo "JOB: $id    $line"
                   break
                fi
            done < "$file"
        fi
    fi
    i=$((${i}+1))
done <<< "$QSTATLIST"

