#!/bin/bash

columnize2 () {
    indent=$1;
    collen=$(($(tput cols)-indent-10));
    keyname=$2;
    value=$3;
    base_indent=$indent
    while [ -n "$value" ] ; do
        #printf "%-${base_indent}s %-${indent}s\n" "$keyname" "${value:0:$collen}";
        printf "%-${indent}s %s\n" "$keyname" "${value:0:$collen}";
        keyname="";
        value=${value:$collen};
        indent=$((base_indent+8));
    done
}

QSTATLIST=$(qstat)

i=0

while read -r qline; do
    if [ $i -ge 2 ]
    then
        id=${qline:0:7}
        file="qsub_logs/job.sh.o${id}"
        if [ -f "$file" ]
        then
            while IFS='' read -r line || [[ -n "$line" ]]; do
                if [[ $line == *"Running:"* ]]; then
                   disp_text="JOB: $id    $line"

                   IFS='' read -r line
                   NUM_TRACKERS=${line:10:5}
                   NUM_SEQUENCES=${line:27:6}
                   TOTAL_EVALUATIONS=$((NUM_TRACKERS * NUM_SEQUENCES))

                   NUM_EVALUATIONS_DONE=$(grep -wc "FPS:" $file)
                   status_text="STATUS: $NUM_EVALUATIONS_DONE / $TOTAL_EVALUATIONS"

                   columnize2 50 "${disp_text}" "${status_text}"
                   break
                fi
            done < "$file"
        fi
    fi
    i=$((${i}+1))
done <<< "$QSTATLIST"

